name: "PaperPluginTemplate"
version: "${version}"
authors:
  - SQD Studios

main: net.chamosmp.PaperPluginTemplate
#Loader: net.chamosmp.

api-version: "1.21.11"
website: https://github.com/SQD-Studios/paper-plugin-template

folia-supported: true


dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true